EXPERIMENT:
  NAME: ""
  TAG: "Uni,res34,res18"
  PROJECT: "uni_imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "UniLogitsKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
Uni:
  TEMPERATURE: 1
  ALPHA: 1.0
  BETA: 0.5
  WARMUP: 1
  INPUT_SIZE: (224, 224)
  CLASS_NUM: 1000
  LATENT_DIM: 1024
