EXPERIMENT:
  NAME: ""
  TAG: "UniKD, fitnet&kd, vx-1-2"
  PROJECT: "unikd_loss_vis_v1"
DISTILLER:
  TYPE: "UniKDFitKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "base_aug"