EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "imagenet_mvkd_v1"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "MVKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
#  TRAINER: "double"
FITNET:
  INPUT_SIZE : (224, 224)
MVKD:
  HINT_LAYER: 3
  CONDITION_DIM: 1512
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 1.0
    REC_WEIGHT: 0.1
    INFER_WEIGHT: 0.01
  DIFFUSION:
    SAMPLE_STEP: 1
    DIFF_FEATURE_NUM: 3
    USE_CONDITION: True

