EXPERIMENT:
  NAME: ""
  TAG: "UniML&KR,res56,res20"
  PROJECT: "res11to32_mlkdmulti_v1"
DISTILLER:
  TYPE: "UniMLKD"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
Uni:
  BETA: 2.0
  OUT_SHAPES: [1, 8, 16, 32]
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [16, 32, 64, 64]
  MAX_MID_CHANNEL: 128