EXPERIMENT:
  NAME: ""
  TAG: "UniML&KR,res56,res20"
  PROJECT: "res324to84_mlkdmulti_v1"
DISTILLER:
  TYPE: "UniMLKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
Uni:
  ALPHA: 1.0
  BETA: 8.0
  TEMPERATURE: 4.0
  WARMUP: 20
  OUT_SHAPES: [1, 8, 16, 32]
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [16, 32, 64, 64]
  MAX_MID_CHANNEL: 128