EXPERIMENT:
  NAME: ""
  TAG: "v1-1-1"
  PROJECT: "r50_mb2_mlkdmulti_v1"
DISTILLER:
  TYPE: "UniMLKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
Uni:
  BETA: 6.0
  SHAPES: [1,2,4,8,16]
  OUT_SHAPES: [1,4,8,16,32]
  IN_CHANNELS: [12,16,48,160,1280]
  OUT_CHANNELS: [256,512,1024,2048,2048]
  MAX_MID_CHANNEL: 256
  #mini test