EXPERIMENT:
  NAME: ""
  TAG: "v1-1-1"
  PROJECT: "wrn402tosv1_mlkdmulti_v1"
DISTILLER:
  TYPE: "UniMLKD"
  TEACHER: "wrn_40_2"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
Uni:
  BETA: 6.0
  SHAPES: [1,4,8,16]
  OUT_SHAPES: [1,8,16,32]
  IN_CHANNELS: [240,480,960,960]
  OUT_CHANNELS: [32,64,128,128]
  MAX_MID_CHANNEL: 256