EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "mvkd_50_mb2_v1"
DISTILLER:
  TYPE: "MVKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
#  TRAINER: "double"
MVKD:
  HINT_LAYER: 3
  CONDITION_DIM: 1536
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 1.0
    REC_WEIGHT: 0.1
    INFER_WEIGHT: 0.01
  DIFFUSION:
    SAMPLE_STEP: 1
    DIFF_FEATURE_NUM: 3
    USE_CONDITION: True
