EXPERIMENT:
  NAME: ""
  TAG: "480epoch, res56_20, vx-1-1"
  PROJECT: "MM_DFKD_v3"
DISTILLER:
  TYPE: "DFKD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "dfkd"
LOG:
  WANDB: True
DFKD:
  SERACH_EPOCH: 20
  AREA_NUM: 8
  HINT_LAYER: 2
  DFKD_TEMPERATURE: 0.5
  LOSS:
    CE_WEIGHT: 1.0
    AUG_FEAT_WEIGHT: 1000.0
    DAM_AREA_WEIGHT: 1000.0