EXPERIMENT:
  NAME: ""
  TAG: "v3-1-x"
  PROJECT: "MM_DFKD_res324_84_v2"
DISTILLER:
  TYPE: "DFKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "dfkd"
LOG:
  WANDB: True
DFKD:
  SERACH_EPOCH: 20
  AREA_NUM: 4
  HINT_LAYER: 2
  DFKD_TEMPERATURE: 1.0
  LOSS:
    CE_WEIGHT: 1.0
    AUG_FEAT_WEIGHT: 100.0
    DAM_AREA_WEIGHT: 1000.0
