EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "dfkd_402_401_v1"
DISTILLER:
  TYPE: "DFKD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TTRAINER: "dfkd"
