EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "fitnet_kd_v1"
DISTILLER:
  TYPE: "Hybrid"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
REVIEWKD:
  OUT_SHAPES: [ 1, 8, 16, 32 ]
  IN_CHANNELS: [ 64,128,256,256 ]
  OUT_CHANNELS: [ 64,128,256,256 ]
  MAX_MID_CHANNEL: 128