EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "DFKD_res324_84_v1"
DISTILLER:
  TYPE: "DFKDReviewKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "dfkd"
REVIEWKD:
  DFKD_CE_WEIGHT: 1.0
  DFKD_REVIEWKD_WEIGHT: 1.0
  DFKD_KD_WEIGHT: 1.0
DFKD:
  SERACH_EPOCH: 20
