EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "dfkdrk_402_401_v1"
DISTILLER:
  TYPE: "DFKDReviewKD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "dfkd"
DFKD:
  OUT_SHAPES: [ 1, 8, 16, 32 ]
  IN_CHANNELS: [ 16, 32, 64, 64 ]
  OUT_CHANNELS: [ 32, 64, 128, 128 ]
  MAX_MID_CHANNEL: 256
  LOSS:
    CE_WEIGHT: 1.0
    KD_WEIGHT: 1.0
    FEAT_WEIGHT: 1.0
