EXPERIMENT:
  NAME: ""
  TAG: "vx-1-1"
  PROJECT: "ReviewKDFKD_r34_18"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "DFKDReviewKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "dfkd"
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DFKD:
  WARMUP_EPOCHS: 1
  SHAPES: [1,7,14,28,56]
  OUT_SHAPES: [1,7,14,28,56]
  IN_CHANNELS: [64,128,256,512,512]
  OUT_CHANNELS: [64,128,256,512,512]
  STU_PREACT: True
  SERACH_EPOCH: 5
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 1.0
    KD_WEIGHT: 1.0
