EXPERIMENT:
  NAME: ""
  TAG: "v30-1-1"
  PROJECT: "imagenet_mlkd_v1"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "UniMLKD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
KD:
  TEMPERATURE: 1
  LOSS:
    CE_WEIGHT: 0.5
    KD_WEIGHT: 0.5
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
Uni:
  CLASS_NUM: 1000
  BETA: 2.0
  TEMPERATURE: 1.0
  SHAPES: [1,7,14,28,56]
  OUT_SHAPES: [1,7,14,28,56]
  IN_CHANNELS: [64,128,256,512,512]
  OUT_CHANNELS: [64,128,256,512,512]
  STU_PREACT: True