EXPERIMENT:
  NAME: ""
  TAG: "7.2x,vx,res32x4,res8x4,xx"
  PROJECT: "cifar100_RegKD_v2"
DISTILLER:
  TYPE: "RegKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

