EXPERIMENT:
  NAME: ""
  TAG: "vx, [0.95, 8, 1, 8, 1, 3]"
  PROJECT: "cifar100_RegKD_Res56_Res20_v2"
DISTILLER:
  TYPE: "RegKD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

RegKD:
  AREA_NUM: 8
  HINT_LAYER: -1
  CHANNEL_MASK: 0.95
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 2.0
  T: 4.0
  WARMUP: 20
  CHANNEL_KD_WEIGHT: 1.0
  AREA_KD_WEIGHT: 3.0

