EXPERIMENT:
  NAME: ""
  TAG: "vx-x-x,[12,1,1,1,-2]"
  PROJECT: "cifar100_r56_r20_RegKD_Final_v2"
DISTILLER:
  TYPE: "RegKD_KR"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

RegKD:
  AREA_NUM: 8
  HINT_LAYER: -1
  CHANNEL_MASK: 0.95
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 2.0
  T: 4.0
  WARMUP: 20
  CHANNEL_KD_WEIGHT: 1.0
  AREA_KD_WEIGHT: 3.0
  SHAPES: [1, 8, 16, 32]
  OUT_SHAPES: [1, 8, 16, 32]
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [16, 32, 64, 64]
  MAX_MID_CHANNEL: 128

