EXPERIMENT:
  NAME: ""
  TAG: "7.23,vx,res56,res20"
  PROJECT: "cifar100_RegKD_V3"
DISTILLER:
  TYPE: "RegKD"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
