EXPERIMENT:
  NAME: ""
  TAG: "dkd,res110,res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "Hybrid"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
REVIEWKD:
  OUT_SHAPES: [1, 8, 16, 32]
  IN_CHANNELS: [16, 32, 64, 64]
  OUT_CHANNELS: [16, 32, 64, 64]
  MAX_MID_CHANNEL: 128