EXPERIMENT:
  NAME: ""
  TAG: "dkd,res110,res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "Hybrid"
  TEACHER: "vgg13"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
REVIEWKD:
  SHAPES: [1,4,4,8,16]
  OUT_SHAPES: [1,4,4,8,16]
  IN_CHANNELS: [128,256,512,512,512]
  OUT_CHANNELS: [128,256,512,512,512]
  MAX_MID_CHANNEL: 128