EXPERIMENT:
  NAME: ""
  TAG: "dkd,res110,res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "Hybrid"
  TEACHER: "wrn_40_2"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 6.0
REVIEWKD:
  SHAPES: [1,4,8,16]
  OUT_SHAPES: [1,8,16,32]
  IN_CHANNELS: [240,480,960,960]
  OUT_CHANNELS: [32,64,128,128]
  MAX_MID_CHANNEL: 256
  REVIEWKD_WEIGHT: 5.0