EXPERIMENT:
  NAME: ""
  TAG: "vx-1-2"
  PROJECT: "mvkd_324_84_v1"
DISTILLER:
  TYPE: "MixKD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240d
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "aug"
