EXPERIMENT:
  NAME: ""
  TAG: "vtest-5-1"
  PROJECT: "cifar100_UniLogits_test"
DISTILLER:
  TYPE: "UniLogitsKD"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
Uni:
  BETA: 2.0
