EXPERIMENT:
  NAME: ""
  TAG: "vtest-5-1"
  PROJECT: "cifar100_UniLogits_test"
DISTILLER:
  TYPE: "UniLogitsKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
Uni:
  HINT_LAYER: 3
  ALPHA: 1.0
  BETA: 8.0
  T: 4.0
  WARMUP: 20


