EXPERIMENT:
  NAME: ""
  TAG: "7.3, v1, srt,res32x4,res8x4"
  PROJECT: "cifar100_srt_cross"
DISTILLER:
  TYPE: "SRT"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR_DECAY_STAGES: [150, 180, 210]
  LR: 0.05
  # EPOCHS: 480
  # LR_DECAY_STAGES: [300, 360, 420]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

